collection: # You can add your own names per ID, they will be shown in Shortcut
  my_chan: -xxxxxxxxxxxxxx # Channel ID
  bhl_channel: -xxxxxxxxxxxxxx # Channel ID
  bhl_group: -xxxxxxxxxxxxxxx # Related group ID
