name: Publish Docker image

on:
  push:
    branches:
      - master
      - develop
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: docker-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "tag=develop" >> $GITHUB_ENV
          fi

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/ulysses-tg:${{ env.tag }} .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.actor }}/ulysses-tg:${{ env.tag }}
