name: Publish Docker image

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/ulysses-tg:latest .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.actor }}/ulysses-tg:latest
